### ISSUE TITLE
reARMP Error

### ISSUE THREAD

**Issue by shun9092** [CapitanRetraso/reARMP#3]
I get an error when I converse back from json to bin.

This file
https://drive.google.com/file/d/1lDctg7wb1Szq6IoDbRx7rfchPRbCztcP/view?usp=sharing

======================================
Traceback (most recent call last):
  File "reARMP.py", line 977, in <module>
  File "reARMP.py", line 974, in determineFileExtension
  File "reARMP.py", line 660, in rebuildFile
  File "reARMP.py", line 920, in importTable
  File "reARMP.py", line 683, in importTable
  File "reARMP.py", line 643, in storeJSONInfo
IndexError: list index out of range
[11856] Failed to execute script reARMP
======================================

**Comment by CapitanRetraso** [comment]
Thank you for reporting this issue. 
It has been fixed in b11efa96f823cf8b8e449ba59b716d3386ba80fd

**Comment by shun9092** [comment]
Can you convert it to a file like csv instead of json when you extract it with this program?

json files are difficult to modify, but I hope there is an easy way.

**Comment by shun9092** [comment]
those file doesn't work

https://drive.google.com/file/d/1QriVLkCUIVn3A4EKIhknGtTp6-m7Lmc1/view?usp=sharing

Pointer to Main Table: 3108
Row Count: 48
Column Count: 5
Text Count: 36
Pointer to String Offset Table: 0
Pointer to Bits Array Table: 3172
Pointer to Byte Array Table: 4688
Pointer to Int Array Table: 4928
Pointer to Text Offset Table: 4544
Pointer to String Offset Table 2: 3232
Pointer to Int Array Table 2: 4960
Pointer to Int Array Table 3: 5152
Pointer to Bit Array Table 2: 3184
Pointer to Another Table: 2916
Pointer to Column Type Table: 0
Pointer to Byte Array Table 3: 2

Exporting...
Traceback (most recent call last):
  File "reARMP.py", line 980, in <module>
  File "reARMP.py", line 977, in determineFileExtension
  File "reARMP.py", line 580, in exportFile
  File "reARMP.py", line 403, in exportTable
KeyError: ''
[8432] Failed to execute script reARMP

/////////////////////////////////////////////////////////

https://drive.google.com/file/d/19FeBNyXtgvefiGs5ywNqHLS2cs0jtp10/view?usp=sharing

Pointer to Main Table: 32
Row Count: 5
Column Count: 2
Text Count: 0
Pointer to String Offset Table: 176
Pointer to Bits Array Table: 96
Pointer to Byte Array Table: 240
Pointer to Int Array Table: 288
Pointer to Text Offset Table: 240
Pointer to String Offset Table 2: 224
Pointer to Int Array Table 2: 304
Pointer to Int Array Table 3: 324
Pointer to Bit Array Table 2: 112
Pointer to Another Table: 0
Pointer to Column Type Table: 0
Pointer to Byte Array Table 3: 0

Exporting...
Traceback (most recent call last):
  File "reARMP.py", line 980, in <module>
  File "reARMP.py", line 977, in determineFileExtension
  File "reARMP.py", line 580, in exportFile
  File "reARMP.py", line 403, in exportTable
KeyError: ''
[18056] Failed to execute script reARMP

**Comment by CapitanRetraso** [comment]
There are no current plans on changing the output format to csv.

Also, those issues are already known (you can check the compatibility list [here](https://docs.google.com/spreadsheets/d/1K39wQyDMbQJT2IoSpjHZBecdaq7Zb3XjEInxYHNJkus/edit?usp=sharing)) but they are low priority as of now because they don't affect important files. 
A fix will be released in the future once more important features get added (support for v2 armp files)

**Comment by shun9092** [comment]
There are some files of this type.
For example, there are options for conversation and tutorial pop-up windows.
Can these files be supported?

https://imgur.com/pDeporC.png

https://i.imgur.com/BgWj55n.png

This file is Yakuza6
File is 'talk.par' → 'ins' folder → 'kamuro_info.par' → 'cmn.par' → 'cmn.bin'
and
'talk.par' → 'main' folder → 'c01' folder → 'adv01_085_03_serena.par' → 'cmn.par' → 'cmn.bin'
 
This is 'talk.par' archive file
https://drive.google.com/file/d/1dbZVHwKa7Vu3KTZwuuV5wBxJvlM2wV3R/view?usp=sharing

**Comment by CapitanRetraso** [comment]
HACT cmn files have nothing to do with armp files and wont be supported

**Comment by shun9092** [comment]
Do you have any information about these files?

The script inside these files needs to be modified, but there is no information, so it is difficult to modify them.

**Comment by CapitanRetraso** [comment]
There is some barebones document in the Yakuza Modding discord. 
However, these formats have nothing to do with armps or this tool so I'll have to ask you to stay on topic here.

**Comment by shun9092** [comment]
Could you tell me if you have a discord for a modding like localizing?

**Comment by CapitanRetraso** [comment]
We only have a [discord](https://discord.com/invite/WQutWJq) for general modding, no idea if one for localization exists
