### ISSUE TITLE
Export error, db.judge.en.par\en\sound_auth.bin

### ISSUE THREAD

**Issue by BioGenx2b** [CapitanRetraso/reARMP#6]
Trying to export sound_auth.bin from the Steam release of Judgment.
Unable to export due to a script error.

`CMD\>reARMP.exe sound_auth.bin

                       _____   __  __  _____
                /\    |  __ \ |  \/  ||  __ \
  _ __  ___    /  \   | |__) || \  / || |__) |
 | '__|/ _ \  / /\ \  |  _  / | |\/| ||  ___/
 | |  |  __/ / ____ \ | | \ \ | |  | || |
 |_|   \___|/_/    \_\|_|  \_\|_|  |_||_|     v0.11.2

Pointer to Main Table: 1634896
Row Count: 138
Column Count: 6
Text Count: 0
Pointer to Row Names Offset Table: 1637984
Pointer to Row Validity Array: 1634976
Pointer to Column Data Types: 1638600
Pointer to Column Content Offset Table: 1639712
Pointer to Text Offset Table: 0
Pointer to Column Names Offset Table: 1638576
Pointer to Row Index Array: 1639736
Pointer to Column Index Array: 1640288
Pointer to Column Validity Array: 1635000
Pointer to SubTable: 0
Pointer to is_empty Bitmask Pointer Table: 0
Pointer to Auxiliary Column Data Types: 0
Pointer to ValidityBool Array/Special Field Indices: 0
Row Validator: 0
Column Validator: 0
Table ID: 934

Exporting...
Entry 1 / 138
Pointer to Main Table: 14608
Row Count: 203
Column Count: 13
Text Count: 0
Pointer to Row Names Offset Table: 0
Pointer to Row Validity Array: -1
Pointer to Column Data Types: 14696
Pointer to Column Content Offset Table: 17568
Pointer to Text Offset Table: 0
Pointer to Column Names Offset Table: 0
Pointer to Row Index Array: 0
Pointer to Column Index Array: 0
Pointer to Column Validity Array: 14688
Pointer to SubTable: 13648
Pointer to is_empty Bitmask Pointer Table: 0
Pointer to Auxiliary Column Data Types: 0
Pointer to ValidityBool Array/Special Field Indices: 0
Row Validator: -1
Column Validator: 0
Table ID: 386

Exporting...
Traceback (most recent call last):
  File "reARMP.py", line 1487, in <module>
  File "reARMP.py", line 1485, in determineFileExtension
  File "reARMP.py", line 747, in exportFile
  File "reARMP.py", line 607, in exportTable
  File "reARMP.py", line 600, in exportTable
IndexError: list index out of range
[126856] Failed to execute script 'reARMP' due to unhandled exception!`

**Comment by zveryga5** [comment]
I was able to decompress with a little editing of the source, but backwards is the problem.

**Comment by deseven** [comment]
Although I have very little experience with binary parsing, it seems that indeed the input file defines a string data (type 13), but there is no string present. If that's true and we're assuming that the logic of getting the string data in the first place is sound, the fix would be to simply check if the string was found.

Add a check to line 598:
```python
if (index == -1 or index >= len(textTable)):  # Check if index is within bounds
    continue
columnData = {str(column) : textTable[index]}
columnDict[row].update(columnData)
```
